// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_Entity_Framework.Data.Models;

public partial class Articulo
{
    public int IdArticulo { get; set; }

    public string Nombre { get; set; }

    public bool Activo { get; set; }

    public decimal? PreUnitario { get; set; }

    public virtual ICollection<DetalleFactura> Detallesfacturas { get; set; } = new List<DetalleFactura>();
}