// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_Entity_Framework.Data.Models;

public partial class DetalleFactura
{
    public int IdDetalleFactura { get; set; }

    public int Cantidad { get; set; }

    public int NroFactura { get; set; }

    public int IdArticulo { get; set; }

    public virtual Articulo IdArticuloNavigation { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }
}