// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_Entity_Framework.Data.Models;

public partial class Factura
{
    public int NroFactura { get; set; }

    public DateOnly Fecha { get; set; }

    public string Cliente { get; set; }

    public int IdFormaPago { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<DetalleFactura> Detallesfacturas { get; set; } = new List<DetalleFactura>();

    public virtual FormaPago IdFormaPagoNavigation { get; set; }
}